apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-sltsatiu
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/go-sltsatiu:azure-5d50cf0537903ea78c7768ea67b8cf78199dfa65
        name: container-image  
